# Generated by Django 5.0.1 on 2024-01-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media")),
                ("sname", models.CharField(max_length=50)),
                ("quantity", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("description", models.CharField(max_length=500)),
            ],
        ),
    ]
